spring:
  profiles:
    active: prod
  config:
    import: optional:env.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  # Lectura del archivo sql
  sql:
    init:
      mode: always
      data-locations-classpath: import.sql
