spring:
  cloud:
    gateway:
      routes:
        - id: userRoute
          uri: http://localhost:8082/msvc-users-api
          predicates:
            - Path=/users/**
        - id: oauthRoute
          uri: lb://msvc-oauth-server
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1